server:
  port: 8000

spring:
  application:
    name: cfl-jd
  datasource:
    url: jdbc:mysql://localhost:3306/hungry
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minPoolSize: 3
    maxPoolSize: 10
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    mainteanceInterval: 60
    maxIdleTime: 60

  ## Redis
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: 123456
    timeout: 800
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 0



# rabbitmq连接参数
  rabbitmq:
    host: 127.0.0.1  # mq ip地址
    port: 5672 # 端口 默认5672
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: /vhost01
  # 开启发送确认(开启此模式，生产者成功发送到交换机后执行相应的回调函数)
  #spring.rabbitmq.publisher-confirms=true
  # 开启发送失败退(开启此模式，交换机路由不到队列时执行相应的回调函数)
  #spring.rabbitmq.publisher-returns=true
  # 开启消费者手动确认 ACK 默认auto
  #spring.rabbitmq.listener.direct.acknowledge-mode=manual
  #spring.rabbitmq.listener.simple.acknowledge-mode=manual

# mail
  mail:
   host: smtp.qq.com
   username: 1696741038@qq.com
   password: fnlrignacikzcagc
   port: 587 #端口号465或587
   protocol: smtp
   default-encoding: UTF-8
   smtp:
     connectiontimeout: 5000
     timeout: 3000
     writetimeout: 5000



mybatis:
  mapper-locations: classpath:com/cfl/myproject/dao/mapper/*.xml
#  type-aliases-package: com.example.entity


customize:
  exception:
   email: 603088455@qq.com


